Add customCheckboxSource render prop
tableflip/react-native-select-multiple pull request #20
Opened 2018-02-18 09:50 UTC by HichamELBSI

Hi, 

A quick fix to https://github.com/tableflip/react-native-select-multiple/issues/7

Regards

2018-02-27 19:44 UTC, HichamELBSI commented
Hi @alanshaw, did i mess something else ?

2018-02-27 19:55 UTC, alanshaw requested changes

2018-02-27 19:55 UTC, alanshaw commented on src/SelectMultiple.js
>          <View style={rowStyle}>
No merged row styles if `renderCustomCheckboxSource`?

2018-02-27 19:55 UTC, alanshaw commented on src/SelectMultiple.js
> +      renderCustomCheckboxSource,
rename to just `renderCheckbox`?

2018-03-05 17:18 UTC, HichamELBSI commented
Hey @alanshaw, what do you think about the last commit ? 😅 sorry for spamming you man

2019-04-12 09:41 UTC, alanshaw commented
@HichamELBSI no worries sorry for the delay, can you please rebase?

2019-10-15 11:49 UTC, alanshaw commented
ping @HichamELBSI

2020-01-30 11:43 UTC, Jacklol commented
what problem width custom checkbox? i need this too. can I help?

2023-11-15 14:32 UTC, closed without merging